# Generated by Django 5.1.3 on 2024-12-09 06:40

import store.custom_field
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("is_homepage", store.custom_field.CustomBooleanField()),
                (
                    "layout",
                    models.CharField(
                        choices=[("list", "List"), ("grid", "Grid")],
                        default="list",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("publish", "Publish")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("ordering", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Category",
            },
        ),
    ]
