# Generated by Django 5.1.3 on 2024-12-09 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_rename_category_categorystore_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CategoryStore",
            new_name="Category",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Category"},
        ),
    ]
