# Generated by Django 5.1.3 on 2024-12-07 01:07

import news.helpers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_alter_article_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("special", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("publish", "Publish")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("ordering", models.IntegerField(default=0)),
                ("link", models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(upload_to=news.helpers.get_file_path),
        ),
    ]
