# Generated by Django 5.1.3 on 2024-12-09 06:25

import news.custom_field
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_feed_alter_article_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name_plural": "Article"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Category"},
        ),
        migrations.AlterModelOptions(
            name="feed",
            options={"verbose_name_plural": "Feed"},
        ),
        migrations.AlterField(
            model_name="article",
            name="special",
            field=news.custom_field.CustomBooleanField(),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_homepage",
            field=news.custom_field.CustomBooleanField(),
        ),
        migrations.AlterField(
            model_name="feed",
            name="special",
            field=news.custom_field.CustomBooleanField(),
        ),
    ]
