# Generated by Django 5.1.3 on 2024-12-10 05:55

import store.custom_field
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_alter_category_options_remove_category_is_homepage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_sub",
            field=store.custom_field.CustomBooleanField(),
        ),
    ]
